apiVersion: v1
kind: Service
metadata:
  name: angular-ui-frontend
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular-ui
    role: frontend
  sessionAffinity: None
  type: LoadBalancer