apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui-frontend-production
spec:
  replicas: 
  selector:
    matchLabels:
      app: angular-ui-frontend
      role: frontend
      env: production
  template:
    metadata:
      name: frontend
      labels:
        app: angular-ui-frontend
        role: frontend
        env: production
    spec:
      containers:
      - image: gcr.io/primeval-mark-254911/angular-ui:1.0.0
        name: frontend
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        ports:
        - name: frontend
          containerPort: 80


